### ISSUE TITLE
extensive documentation about core

### ISSUE THREAD

**Issue by brunobord** [workalendar/workalendar#39]
the core.py modules starts to become a bit too big. It'd be great to have a helpful documentation about its internals and how to use the Mixins.

**Comment by JanMalte** [comment]
Do you prefer an inline documentation in class comments or a separate in the README?

**Comment by brunobord** [comment]
I think it'd be better to have a sphinx documentation available on RTFD. Eventually using autodoc to load docstrings when they're useful enough. The "usage" part is covered by the README, but the internals is more "dev" oriented, so the docstrings should target this audience.
There's also a "tutorial" section in the CONTRIBUTING document.

Once again, it might be worth it to give a shot at organising a comprehensive complete documentation on how to use workalendar, how to contribute to it by adding a calendar, or how to contribute to it by suggesting improvements.
