### ISSUE TITLE
Add support for Philippines Holidays

### ISSUE THREAD

**Issue by micodls** [workalendar/workalendar#396]
Sources: https://www.timeanddate.com/holidays/philippines/

**Comment by Natim** [comment]
@micodls are you able to start a PR to [contribute the calendar](https://github.com/peopledoc/workalendar/blob/master/contributing.md#adding-new-calendars)?

**Comment by micodls** [comment]
I can try do this over the week.

**Comment by brunobord** [comment]
I'd be glad to review your pull-request when it's ready.
Do not hesitate to cross-check holidays with [Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_the_Philippines) or any other official resources you can find about it.

**Comment by brunobord** [comment]
The latest release (16.0.0) includes your fresh-new Philippines calendar. Congrats!

* https://pypi.org/project/workalendar/16.0.0/
* https://github.com/workalendar/workalendar/releases/tag/16.0.0

Happy upgrading!
