### ISSUE TITLE
Issue with PyInstaller

### ISSUE THREAD

**Issue by SimoneD89** [workalendar/workalendar#657]
According to http://pyinstaller.47505.x6.nabble.com/Help-Failed-to-execute-script-td2705.html apparently there is an issue with workalendar's __init__ that makes it incompatible with PyInstaller.

I tried their "very hacky fix"  and it works. It would be nice if you could fix your __init__.

I tried with python 3.9.5 and workalendar 15.3.0.
Thank you in advance.
SD

**Comment by ewjoachim** [comment]
Would it be ok if we replaced this `__init__` with [an importlib_metadata with a fallback](https://github.com/cjolowicz/hypermodern-python/blob/master/src/hypermodern_python/__init__.py) and [a dependency to importlib_metadata only on older Pythons](https://github.com/cjolowicz/hypermodern-python/blob/master/pyproject.toml#L19) ?

**Comment by ewjoachim** [comment]
(Also, if yes, would you be interested in doing it ?)

**Comment by SimoneD89** [comment]
I have no clue how to fix things. I use python as a tool for data analysis and I don't have enough experience.

If needed I could help testing solutions (but as I said I lack of experience).

Thanks

**Comment by ewjoachim** [comment]
Ok if @brunobord agrees, I'll do the modification, which I believe is a good idea anyway, and once it's released, you can try again and tell us if it solved your problem.

**Comment by SimoneD89** [comment]
Thank you for your fix. I tried the new version but the problem is still there. I guess the fix will be merged in future releases. Thank you again for your time.

**Comment by ewjoachim** [comment]
Yes, the PR above hasn't been merged yet.
There are multiple ways to test this:
1. wait for the PR to be merged and a subsequent release of workalendar
2. build the package wheel yourself from my branch and use it to test
3. build the package yourself and upload it to a dedicated index that you'll use (if you want some more info for this, let me know)

**Comment by SimoneD89** [comment]
I builded the package from your branch and it works!

Thanks again,
SD

**Comment by ewjoachim** [comment]
Hm, I suggest we reopen until my PR is merged...

**Comment by brunobord** [comment]
I think I'm going to make a Release Candidate and publish it on PyPI.
Then you'll be able to use it and test if nothing's broken in the meantime.
Are you okay with this?

**Comment by SimoneD89** [comment]
That would be great. Thank you for the support.
SD

**Comment by SimoneD89** [comment]
I confirm that in the branch release-candidate/15.5.0rc1 the pyinstaller issue is solved.

**Comment by brunobord** [comment]
@SimoneD89 that's super cool. If I may, could you please make one tiny last test using the release candidate files? https://pypi.org/project/workalendar/15.5.0rc1/

**Comment by SimoneD89** [comment]
The compiled scripts work fine with workalendar 15.5.0rc1 installed from pypi. Thank you for your support!

Summary:
workalendar 15.4.0: compiled scripts are not executing
workalendar 15.5.0rc1: pyinstaller issue solved and compiled scripts work fine
