### ISSUE TITLE
Holiday in Japan during Jul to Aug are incorrect.

### ISSUE THREAD

**Issue by lxlgarnett** [workalendar/workalendar#662]
workalendar version: 15.3.0
python version: 3.8.10 
extensive details on the country / area Calendar: Japan / asia

The following dates on Japan calendar was incorrect.
- Marine Day (2021/7/19) was changed to 2021/7/22 this year
- Health and Sports Day(2021/10/11) was changed to 2021/7/23 this year.
- Mountain Day(2021/8/11) was changed to 2021/8/8 this year.
  - because of 2021/8/8 is Sunday, 2021/8/9 is also a holiday.
![Screen Shot 2021-07-01 at 10 43 35](https://user-images.githubusercontent.com/7702241/124052377-3faa4500-da59-11eb-81cf-4c283b57b805.png)

**Comment by ewjoachim** [comment]
Is there a general rule that some days will always be shifted when they are a specific day of the week or something, or is it something that is decided arbitrarily by Japan authorities every year ? (my real question is: if we fix it for this year, will we have the same problem next year too ?)

**Comment by lxlgarnett** [comment]
The current logic is correct. The Japanese government change the holiday only for this year because of the Olympics. 
Here is the statement from the Japanese government.(Sorry it is in Japanese.)
```
令和３年（２０２１年）の祝日について
令和３年（2021年）に限り、「海の日」は7月22日に、「スポーツの日」は7月23日に、「山の日」は8月8日(※）になります。

平成三十二年東京オリンピック競技大会・東京パラリンピック競技大会特別措置法等の一部を改正する法律（令和2年法律第68号）が本年12月28日に施行されることに伴い、改正後の令和三年東京オリンピック競技大会・東京パラリンピック競技大会特別措置法（平成27年法律第33号）第32条第2項の規定に基づき、令和3年（2021年）における海の日、スポーツの日及び山の日については、上記の通りとなります。

（※）国民の祝日に関する法律（昭和23年法律第178号）第3条第2項の規定に基づき、8月9日は休日となります。

■祝日移動に関するＱ＆Ａなど、詳しくは、首相官邸ホームページ「２０２１年の祝日移動について」※別ウィンドウで開きますを御参照ください。

※令和２年１２月４日 内閣官房東京オリンピック競技大会・東京パラリンピック競技大会推進本部事務局
```
[Japan government's site](https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html)

**Comment by ewjoachim** [comment]
Awesome thanks :)

Do you want to do the Pull Request for fixing that or would you rather we do it ?

**Comment by ewjoachim** [comment]
For the record, here's a DeepL translation of the above:
```
National Holidays in 2021

In 2021, Umi-no-Hi will be celebrated on July 22, Sports-no-Hi on July 23, and Yama-no-Hi on August 8 (*).

With the enactment of the Act on Partial Revision of the Act on Special Measures for the Tokyo Olympic Games and Tokyo Paralympic Games in 2020 (Act No. 68 of 2000) on December 28, 2021, in accordance with the provisions of Article 32, paragraph 2 of the revised Act on Special Measures for the Tokyo Olympic Games and Tokyo Paralympic Games (Act No. 33 of 2015), the dates of Marine Day, Sports Day, and Mountain Day in 2021 will be as above.

In accordance with Article 3, Paragraph 2 of the Act on National Holidays (Act No. 178 of 1948), August 9 will be a holiday.

For more information, including Q&A regarding the holiday shift, please refer to the website of the Prime Minister's Office, "Holiday Shift in 2021" *This will open in a new window.

December 4, 2020 Secretariat of the Tokyo Olympic Games and Tokyo Paralympic Games Promotion Office, Cabinet Secretariat
```
(Translated with www.DeepL.com/Translator)

**Comment by lxlgarnett** [comment]
> Awesome thanks :)
> 
> Do you want to do the Pull Request for fixing that or would you rather we do it ?

@ewjoachim 
I think I can do the pull request. Do I need to fork the master branch or just create new branch from the master branch to open a pull request?

**Comment by ewjoachim** [comment]
You'll need to fork the repository, and then clone your fork locally. In there, you'll create a new branch (named e.g. `japan-olympics-update`) and then work on that.
Once you've updated the code (in `workalendar/asia/japan.py`) and the tests (in `workalendar/tests/test_asia.py::JapanTest` where you'll add a `def test_year_2021(sel)` method), and add a changelog in `Changelog.md`, you commit it, and push it to your fork, then open a PR from `<your fork>:japan-olympcs-update` to `workalendar:master` and that should be it :)

Thank you !

**Comment by lxlgarnett** [comment]
@ewjoachim 
I opened a PR for this issue.
https://github.com/workalendar/workalendar/pull/663

**Comment by brunobord** [comment]
The latest (15.3.1) Release of Workalendar has been pushed to PyPI. You can now upgrade and enjoy your great patch!

* https://pypi.org/project/workalendar/15.3.1/
* https://github.com/workalendar/workalendar/releases/tag/15.3.1
