### ISSUE TITLE
Should we prepare for a UK surprise Euro-related holiday ?

### ISSUE THREAD

**Issue by ewjoachim** [workalendar/workalendar#670]
https://www.independent.co.uk/news/uk/home-news/euro-2020-england-italy-bank-holiday-final-b1881007.html

It might be possible that UK announces a surprise holiday if they with the Euro. We could prepare a PR and merge it only if confirmed.

**Comment by brunobord** [comment]
well, kinda sorted: https://en.wikipedia.org/wiki/UEFA_Euro_2020#Final
Congratulations, Italy, and also, well done to the England team, you did a remarkable competition.
