### ISSUE TITLE
National Holidays In Brazil

### ISSUE THREAD

**Issue by SCoutinhoEveris** [workalendar/workalendar#676]
Hi,

I am affraid that  **CORPUS CHRISTI** and **CARNIVAL** are not registered in **WORKALENDAR**

**16/02/2021 | tuesday | Carnival
03/06/2021 | friday     | Corpus Christi**

In Brazil, these days are national holidays. Is it possible to add then in WORKALENDAR ?

**RULES:**

- **Carnival** is celebrated 47 days before **Easter**. 
- **Corpus Christi** takes place 60 days after **Easter**.

Best regards,

Sergio Coutinho

**Comment by brunobord** [comment]
I'm afraid I have to disagree.
I see that there's no Corpus Christi or Carnival holiday for the *core* Brazil calendar, but as far as I can say, there's no such thing as a national/federal calendar, and you're going to have to chose between the various territories available (States or Provinces). And some of them include Corpus Christi or Carnival, depending on the local rules.

An example with _São Paulo City_ https://github.com/workalendar/workalendar/blob/master/workalendar/america/brazil.py#L308

Do we agree that this solves your issue?

**Comment by ewjoachim** [comment]
I [see](https://translate.google.com/translate?sl=auto&tl=en&u=https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2021/01/governo-divulga-feriados-e-pontos-facultativos-de-2021) that those holidays are officially "optional" (ponto facultativo). I don't know if we should base ourselves on whether it's mostly observed or not. What is the general process of Workalendar on those cases ?

**Comment by SCoutinhoEveris** [comment]
I am brazilian, so this is why i have sent the advice.

But no problem. If i can see this national holiday (no offence, but it is strange for us in Brazil imagine Carnival as  a local holiday... ) in a city configuration, its sufficient for our needs.

Thank you for the instructions.

Best regards!

Sergio

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SCoutinhoEveris** [comment]
Joachim,

Now I see you are right.
Although Carnival is see here in Brazil as a national holiday (no nome works), it´s “ponto facultativo” by the federative administration.
I think this “issue” (cause it´s really not a issue), can be closed.
Best regards !
Sergio

De: Joachim Jablon ***@***.***
Enviada em: sábado, 24 de julho de 2021 07:02
Para: workalendar/workalendar ***@***.***>
Cc: Sergio Tavares Coutinho ***@***.***>; Author ***@***.***>
Assunto: Re: [workalendar/workalendar] National Holidays In Brazil (#676)


everis Security Awareness - This is an incoming mail from an EXTERNAL DOMAIN. Please verify sender before you open attachments or access links.

I see<https://translate.google.com/translate?sl=auto&tl=en&u=https://www.gov.br/pt-br/noticias/financas-impostos-e-gestao-publica/2021/01/governo-divulga-feriados-e-pontos-facultativos-de-2021> that those holidays are officially "optional" (ponto facultativo). I don't know if we should base ourselves on whether it's mostly observed or not. What is the general process of Workalendar on those cases ?

**Comment by brunobord** [comment]
Obrigado!
