### ISSUE TITLE
Basic usage wrongly documented: datetime.date vs. datetime.datetime

### ISSUE THREAD

**Issue by damarvin** [workalendar/workalendar#690]
In the lower part of https://workalendar.github.io/workalendar/basic.html example

    >>> cal.add_working_days(datetime(2012, 12, 23, 14, 0, 39), 5)
    datetime.datetime(2012, 12, 31)

the output is wrongly given, making the following `keep_datetime=True` option hardly understandable.
Actually the result is

    datetime.date(2012, 12, 31)

which makes more sense here. ;-)

**Comment by brunobord** [comment]
indeed. Will fix this, thanks for the bug report.

**Comment by brunobord** [comment]
The documentation bugfix has been included in the latest release of Workalendar, now available on PyPI!

* https://github.com/workalendar/workalendar/releases/tag/16.3.0
* https://pypi.org/project/workalendar/16.3.0/
