### ISSUE TITLE
PyPI ownership

### ISSUE THREAD

**Issue by ewjoachim** [workalendar/workalendar#692]
I jjust realized I'm a PyPI owner of the workalendar, legacy for the PeopleDoc umbrella times. What should we do ?

- I remove myself from the owners ?
- I leave it as-is
- If you want, I can be a maintainer officially (I don't need the commit bit, but if you want, I can help reviewing etc)

**Comment by ewjoachim** [comment]
![Screenshot from 2021-12-03 15-23-25](https://user-images.githubusercontent.com/1457576/144618252-ee01a70f-6fa4-4f99-8746-a94793e5a33f.png)

BTW, you don't have 2FA activated :) you may want to set it up !

**Comment by brunobord** [comment]
I'll vote for "leave it as-is", to make sure that the bus factor doesn't go down to 1.
