### ISSUE TITLE
Missing conditional holidays for Neuchatel (Switzerland)

### ISSUE THREAD

**Issue by claudep** [workalendar/workalendar#697]
26.12 and 2.1 are holidays in Canton of Neuchatel only when the preceding day is a Sunday.
References:
- https://fr.wikipedia.org/wiki/Jours_fériés_en_Suisse
- https://www.ne.ch/themes/travail/pages/jours-feries.aspx
- http://rsn.ne.ch/DATA/program/books/rsne/pdf/94102.pdf

**Comment by claudep** [comment]
I think I'll also add the Federal Thanksgiving Monday (same sources as above) in the same pull request.

**Comment by brunobord** [comment]
Your bugfix has been included in the latest release of Workalendar, now available on PyPI!

* https://github.com/workalendar/workalendar/releases/tag/16.3.0
* https://pypi.org/project/workalendar/16.3.0/

**Comment by claudep** [comment]
\o/
