### ISSUE TITLE
Workalendar.exceptions.CalendarError: Need configure 2023 for China

### ISSUE THREAD

**Issue by etscript** [workalendar/workalendar#730]
Excuse me, when will update the data of 2023？

**Comment by RyoLee** [comment]
https://github.com/workalendar/workalendar/pull/728

not accepted yet

**Comment by brunobord** [comment]
The latest release of Workalendar (v17.0.0), including the 2023 China holidays, has been published on PyPI. More informations on:

* https://github.com/workalendar/workalendar/releases/tag/17.0.0
* https://pypi.org/project/workalendar/17.0.0/

Happy upgrading!
